// Mocks generated by Mockito 5.4.6 from annotations
// in gwt/test/mock_objects/mock_git_client.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gwt/src/infrastructure/git_client.dart' as _i2;
import 'package:gwt/src/models/worktree.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitClient extends _i1.Mock implements _i2.GitClient {
  MockGitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createBranch(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createBranch, [name]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> createWorktree(String? path, String? branch) =>
      (super.noSuchMethod(
            Invocation.method(#createWorktree, [path, branch]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#createWorktree, [path, branch]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i5.Worktree>> listWorktrees() =>
      (super.noSuchMethod(
            Invocation.method(#listWorktrees, []),
            returnValue: _i3.Future<List<_i5.Worktree>>.value(<_i5.Worktree>[]),
          )
          as _i3.Future<List<_i5.Worktree>>);

  @override
  _i3.Future<void> removeWorktree(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#removeWorktree, [path]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getCurrentBranch() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentBranch, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getCurrentBranch, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> branchExists(String? branch) =>
      (super.noSuchMethod(
            Invocation.method(#branchExists, [branch]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasUncommittedChanges(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#hasUncommittedChanges, [path]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> getBranchStatus(String? branch) =>
      (super.noSuchMethod(
            Invocation.method(#getBranchStatus, [branch]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getBranchStatus, [branch]),
              ),
            ),
          )
          as _i3.Future<String>);
}
