version: "1.0"

copy:
  files: []
  directories: []

hooks:
  timeout: 30
  preAdd: "echo 'Pre-add hook executed'"
  postAdd: "echo 'Post-add hook executed'"

shellIntegration:
  enableEvalOutput: false